# Generated by Django 5.2.11 on 2026-02-10 02:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('value_format', models.CharField(max_length=50)),
                ('value_char', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.IntegerField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('type_list', models.CharField(max_length=255)),
                ('source', models.CharField(default='client', max_length=30)),
                ('lock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('extern_ref_admin_lov', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('sgbd_password', models.TextField(blank=True, null=True)),
                ('priv_key', models.TextField(blank=True, null=True)),
                ('sgbd_host', models.CharField(max_length=255)),
                ('sgbd_user', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_port', models.IntegerField(blank=True, null=True)),
                ('sgbd_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_database', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_tls', models.BooleanField(default=False)),
                ('sgbd_x509', models.BooleanField(default=False)),
                ('sgbd_ca_file', models.TextField(blank=True, null=True)),
                ('sgbd_certificate_key_file', models.TextField(blank=True, null=True)),
                ('sgbd_certificate_file', models.TextField(blank=True, null=True)),
                ('sgbd_certificate_key_file_password', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sgbd_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sgbd', to='tdm_orchestrator.type')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('siret', models.CharField(blank=True, max_length=255, null=True)),
                ('sigle', models.CharField(blank=True, max_length=255, null=True)),
                ('dpo', models.CharField(blank=True, max_length=255, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_dpo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.entity')),
                ('forme_juridique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forme_juridique', to='tdm_orchestrator.type')),
                ('type_entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.type')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('type2', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('data_sources', models.ManyToManyField(blank=True, related_name='application_datasource', to='tdm_orchestrator.datasource')),
                ('entity', models.ManyToManyField(related_name='application_entity', to='tdm_orchestrator.entity')),
                ('type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.type')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique du runner', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nom du runner', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description du scénario', null=True)),
                ('stop_on_error', models.BooleanField(default=True, help_text="Arrêter l'exécution au premier échec ou continuer (best effort)")),
                ('verbose_logging', models.BooleanField(default=False, help_text='Activer les logs détaillés')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('application', models.ForeignKey(help_text='Application cible', on_delete=django.db.models.deletion.PROTECT, related_name='runners', to='tdm_orchestrator.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_runners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Runner',
                'verbose_name_plural': 'Runners',
                'db_table': 'tdm_runner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SqlScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique du script', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nom du script', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du script', null=True)),
                ('script_type', models.CharField(choices=[('PRE', 'Pre-Processing'), ('POST', 'Post-Processing'), ('UTIL', 'Utility')], help_text='Type de script (Pre-Processing, Post-Processing ou Utility)', max_length=10)),
                ('content', models.TextField(help_text='Contenu SQL brut du script (supporte les variables ${VAR})')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('application', models.ForeignKey(help_text='Application cible', on_delete=django.db.models.deletion.PROTECT, related_name='sql_scripts', to='tdm_orchestrator.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sql_scripts', to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(blank=True, help_text='Source de données sur laquelle le script sera exécuté', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sql_scripts', to='tdm_orchestrator.datasource')),
            ],
            options={
                'verbose_name': 'Script SQL',
                'verbose_name_plural': 'Scripts SQL',
                'db_table': 'tdm_sql_script',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunnerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text="Ordre d'exécution dans la séquence (1, 2, 3...)", validators=[django.core.validators.MinValueValidator(1)])),
                ('step_type', models.CharField(choices=[('PRE', 'Pre-Process'), ('POST', 'Post-Process')], help_text="Type d'étape (Pre-Process ou Post-Process)", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('runner', models.ForeignKey(help_text='Runner parent', on_delete=django.db.models.deletion.CASCADE, to='tdm_orchestrator.runner')),
                ('script', models.ForeignKey(help_text='Script SQL à exécuter', on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.sqlscript')),
            ],
            options={
                'verbose_name': 'Étape de Runner',
                'verbose_name_plural': 'Étapes de Runner',
                'db_table': 'tdm_runner_step',
                'ordering': ['step_type', 'order'],
            },
        ),
        migrations.AddField(
            model_name='runner',
            name='scripts',
            field=models.ManyToManyField(help_text='Scripts SQL associés à ce runner', related_name='runners', through='tdm_orchestrator.RunnerStep', to='tdm_orchestrator.sqlscript'),
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILURE', 'Échec'), ('CANCELLED', 'Annulé')], default='RUNNING', help_text="Statut de l'exécution", max_length=50)),
                ('logs', models.TextField(blank=True, help_text='Logs de console (stdout)', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec", null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_column='start_date')),
                ('ended_at', models.DateTimeField(blank=True, db_column='end_date', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text="Durée d'exécution en millisecondes", null=True)),
                ('variables_used', models.JSONField(blank=True, help_text="Variables utilisées lors de l'exécution (format JSON)", null=True)),
                ('executed_by', models.ForeignKey(blank=True, help_text="Utilisateur ayant lancé l'exécution", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sql_executions', to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(blank=True, help_text='Runner exécuté (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='tdm_orchestrator.runner')),
                ('script', models.ForeignKey(blank=True, help_text='Script exécuté (peut être NULL si exécution de runner complet)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='tdm_orchestrator.sqlscript')),
            ],
            options={
                'verbose_name': "Log d'exécution",
                'verbose_name_plural': "Logs d'exécution",
                'db_table': 'tdm_execution_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sqlscript',
            index=models.Index(fields=['script_type', 'is_active', 'is_deleted'], name='tdm_sql_scr_script__c43eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='sqlscript',
            index=models.Index(fields=['application', 'is_active'], name='tdm_sql_scr_applica_0d3a38_idx'),
        ),
        migrations.AddIndex(
            model_name='runnerstep',
            index=models.Index(fields=['runner', 'step_type', 'order'], name='tdm_runner__runner__e8903c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runnerstep',
            unique_together={('runner', 'step_type', 'order')},
        ),
        migrations.AddIndex(
            model_name='runner',
            index=models.Index(fields=['application', 'is_active', 'is_deleted'], name='tdm_runner_applica_e7ab58_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['-started_at'], name='tdm_executi_start_d_54c49a_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['status', '-started_at'], name='tdm_executi_status_c3506a_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['runner', '-started_at'], name='tdm_executi_runner__fd726a_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['script', '-started_at'], name='tdm_executi_script__f2fce7_idx'),
        ),
    ]
